server:
  port: ${PORT:5555}
  
spring:
  application:
    name: zuulserver
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888

eureka: 
  instance: 
    preferIpAddress: true
  client: 
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
      
logging:
  level: 
    com.thoughtmechanix.zuul.filter.pre.TrackingFilter: DEBUG
    com.thoughtmechanix.zuul.filter.post.ResponseFilter: DEBUG