server:
  port: 8761
  
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  #Uncomment when working in a development mode.
  #server:
  #  wait-time-in-ms-when-sync-empty: 5