spring:
  jpa:
    database: "ORACLE"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.Oracle10gDialect"
  datasource:
    platform: "oracle"
    url: "jdbc:oracle:thin:@192.168.11.61:1521:BAHIA"
    username: "UFOREST"
    password: "admin"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
  database:
    driverClassName: "oracle.jdbc.OracleDriver"